# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: ghcr.io/andrii-sosiuk
  name: go-telebot
  tag: 3.0.0-a27c491
  arch: amd64
  pullPolicy: IfNotPresent
secret:
  name: kbot
  tokenKey: token
  tokenName: TELE_TOKEN
