name: Delivery docker image for telebot

on:
  push:
    branches: [ "develop" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Build the Docker image
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test
        run: make test

      - name: ghcr login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_NAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Build&Push
        env:
          APP: "kbot"
          REGISTRY:  ${{ secrets.REGISTRY_NAME }}
        run: make image push

