name: Delivery docker image for telebot

on:
  push:
    branches: [ "develop" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Build the Docker image
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Make build
        run: make build 

      - name: ghcr login
        uses: docker/login-action@3
        with:
          username: ${{ secrets.REGISTRY_NAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

